config/routes.rb
Rails.application.routes.draw do
  root 'gossips#index'
  resources :sessions, only: [:new, :create, :destroy]
  resources :user, only: [:show, :create, :new]
  resources :city, only: [:show]
  resources :likes, only: [:create, :destroy]

  resources :gossips do
    resources :likes, only: [:create, :destroy]
    resources :comments, except: [:index, :new] do
      resources :likes, only: [:create, :destroy]
      resources :comments, except: [:index, :new] do
        resources :likes, only: [:create, :destroy]
      end
    end
  end

  resources :contact, only: [:index]
  resources :team, only: [:index]
  

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord

  validates :name,
            presence: true

  validates :zip_code,
            presence: true

  has_many :users
end

app/models/comment.rb
class Comment < ApplicationRecord

  validates :comment_type_type,
            presence: true

  validates :comment_type_id,
            presence: true

  validates :content,
            presence: true,
            length: { maximum: 200 }

  has_many :likes, as: :like_target
  belongs_to :user
  belongs_to :comment_type, polymorphic: true
  has_many :comments, as: :comment_type
end

app/models/gossip.rb
class Gossip < ApplicationRecord

  validates :title,
            presence: true,
            length: { minimum: 3, maximum: 14 }

  validates :content,
            presence: true

  has_many :likes, as: :like_target
  belongs_to :user
  belongs_to :tag, optional: true
  has_many :comments, as: :comment_type
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :like_target, polymorphic: true
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord

  validates :content,
            presence: true,
            length: { maximum: 2000 }

  validates :sender_id,
            presence: true

  validates :recipient_id,
            presence: true

  belongs_to :sender, class_name: 'User'
  belongs_to :recipient, class_name: 'User'
end

app/models/tag.rb
class Tag < ApplicationRecord

  validates :title,
            presence: true,
            length: { minimum: 3, maximum: 20 }

  has_many :gossips
end

app/models/user.rb
class User < ApplicationRecord

  has_secure_password

  validates :first_name,
            presence: true

  validates :last_name,
            presence: true

  validates :email,
            presence: true,
            uniqueness: true,
            format: {
              with: /\A[^@\s]+@([^@\s]+.)+[^@\s]+\z/,
              message: 'email adress please'
            }

  validates :password,
            presence: true,
            length: { minimum: 6, maximum: 20 }

  validates :description,
            presence: true,
            length: { minimum: 20, maximum: 200 }

  has_many :gossips
  has_many :comments, as: :comment_type
  has_many :likes
  belongs_to :city
  has_many :sent_messages, foreign_key: 'sender_id', class_name: 'PrivateMessage'
  has_many :received_messages, foreign_key: 'recipient_id', class_name: 'PrivateMessage'

  def remember(remeber_token)
    remember_digest = BCrypt::Password.create(remeber_token)
    update(remember_digest: remember_digest)
  end
end

app/controllers/city_controller.rb
class CityController < ApplicationController
  def show
    @city = City.find(params[:id])
  end
end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController

  before_action :authenticate_user, only: [:new, :create, :show]
  before_action :creator?, only: [:edit, :update, :destroy]

  def index
  end

  def show
    @gossip = gossip_find
    @id = params[:id]
  end

  def new
  end

  def create
    @gossip = Gossip.new(
      user: current_user,
      title: params[:title],
      content: params[:content]
    )
    if @gossip.save
      redirect_to gossips_path, alert: 'Potin enregistré !'
    else
      @gossip.errors.messages.each_with_index do |m, index|
        flash.now[:alert] = m[index + 1][0]
      end
      render :new
    end
  end

  def edit
    @gossip = gossip_find
  end

  def update
    @gossip = gossip_find
    if @gossip.update(post_params)
      redirect_to gossips_path, alert: 'Modification enregistrée !'
    else
      flash.now[:alert] = "Le potin n'a pas pu être modifié"
      render :edit
    end
  end

  def destroy
    @gossip = gossip_find

    if @gossip.destroy
      redirect_to gossips_path, alert: 'Suppression réussie !'
    else
      flash.now[:alert] = 'Echec à la suppression !'
      render :show
    end
  end

  private

  def gossip_find
    gossip = Gossip.find(params[:id])
  end

  def creator?
    unless gossip_find.user == current_user
      redirect_to gossip_path(gossip_find.id), alert: "Ce n'est pas votre potin !"
    end
  end

  def post_params
    post_params = params.require(:gossip).permit(:title, :content)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def show
  end
end

app/controllers/team_controller.rb
class TeamController < ApplicationController
  def index 
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def show
    @user = current_user
  end

  def new
  end

  def create

    if exists?(params[:city])
      @city = find_city(params[:city])
    else
      @city = create_city(params[:city], params[:zip_code])
    end

    @user = User.new(
      first_name: params[:first_name],
      last_name: params[:last_name],
      email: params[:email],
      password: params[:password],
      description: params[:description],
      age: params[:age],
      city: @city
    )
    if @user.save
      log_in(@user)
      if params[:remember_user]
        remember(current_user)
      end
      redirect_to gossips_path, alert: "Bienvenue sur The Gossip Project #{current_user.first_name} !"
    else
      flash.now[:danger] = "Votre compte n'a pas pu être créé, vérifiez que vous avez rempli tous les champs"
      render :new
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/city_helper.rb
module CityHelper
  def exists?(city_name)
    return true if City.find_by(name: city_name.downcase)

    false
  end

  def find_city(name)
    City.find_by(name: name)
  end

  def create_city(name, zip_code)
    City.create(name: name.downcase, zip_code: zip_code.downcase)
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
  def liked?(content)
    c_likes = []
    content.likes.each do |l|
      c_likes << l.user
    end
    return true if c_likes.any? { |u| u == User.find_by(id: session[:user_id]) }

    false
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def current_user
    if session[:user_id]
      User.find_by(id: session[:user_id])
    elsif
      cookies[:user_id]
      # Trouver l'utilisateur en DB a partir de son id dans le cookie
      user = user.find_by(id: cookies[:user_id])
      if user
        # Comparaison du remember_token stocke en cookie hashe, avec le hash remember_digest en db
        remember_token = cookies[:remember_token]
        remember_digest = user.remember_digest
        user_authenticated = BCrypt::Password.new(remember_digest).is_password?(remember_token)

        if user_authenticated
          log_in(user)
          current_user = user
        end
      
      end
    end
  end

  def authenticate_user
    unless current_user
       redirect_to new_session_path, alert: 'Vous devez être connecté pour faire cela !'
    end
  end

  def remember(user)
    # Generation d'un token en base64
    remember_token = SecureRandom.urlsafe_base64

    # Stockage en base de donnees
    user.remember(remember_token)

    cookies.permanent[:user_id] = { value: user.id, same_site: :lax }
    cookies.permanent[:remember_token] = { value: remember_token, same_site: :lax }
  end

  def log_in(user)
    session[:user_id] = user.id
  end

  def forget(user)
    user.update(remember_digest: nil)
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

  def log_out(user)
    session.delete(:user_id)
    forget(user)
  end

  def object_creator?(content)
    return true if content.user == current_user

    false
  end

  def logged_in?
    return true unless session[:user_id].nil?

    false
  end
end

app/helpers/team_helper.rb
module TeamHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/gossips/edit.html.erb
<div class="container mt-5">
  <div class="container-fluid">
    <h1 class="mb-5">Editer le potin <%=@gossip.title%></h1>
    <h3 class="text-muted">Par <%=link_to "#{@gossip.user.first_name} #{@gossip.user.last_name}", { controller: 'user', action: 'show', id: @gossip.user.id }, class: 'text-decoration-none'%></h3>

    <% flash.each do |type, msg| %>
      <div class="alert alert-danger">
        <%= msg %>
      </div>
    <% end %>

    <%=form_for @gossip do |f|%>

      <div class="form-group">
        <label>Titre</label>
        <%=f.text_field :title, class: 'form-control'%>
      </div>

      <div class="form-group">
        <label>Contenu</label>
        <%=f.text_area :content, class: 'form-control'%>
      </div>

      <div class="form-group">
        <button type="submit" class="btn btn-primary">Editer</button>
      </div>

    <%end%>
  </div>
</div>

app/views/gossips/index.html.erb
<div class="container">
  <div class="container-fluid text-center mt-5 mb-5">

    <% flash.each do |type, msg| %>
      <div class="alert alert-success">
        <%= msg %>
      </div>
    <% end %>

    <h1 class="display-1">Bienvenue</h1>
    <p class="text-muted">Ici se trouvent tous les potins du site</p>
  </div>

  <div class="container text-center mb-5">
    <h2>Créer un potin</h2>
    <button class="btn btn-primary">
      <%=link_to 'Créer', { controller: 'gossips', action: 'new' }, class: "text-light text-decoration-none"%>
    </button>
  </div>

  <div class="container">
    <%Gossip.all.each do |g|%>
      <div class="card mb-2">
        <div class="card-body">
          <div class="container text-end">
            <h3 class="card-title text-start"><%=g.title%></h3>
            <h5 class="card-text text-muted text-start"><%=g.user.first_name%> <%=g.user.last_name%></h5>
            <small class="text-muted">Comms</small>
            <span class="badge bg-primary rounded-pill"><%=g.comments.size%></span>
          </div>
          <div class="container text-end mt-3">
            <small class="text-muted">Likes</small>
            <span class="badge bg-warning rounded-pill"><%=g.likes.size%></span>
          </div>
          <div class="container d-flex">
            <div style="margin-right: 1rem;">
              <%=link_to 'Voir', gossip_path(g.id), class: "btn btn-primary"%>
            </div>
            <%if !object_creator?(g)%>
              <%if liked?(g)%>
                <%=button_to "Je n'aime plus", like_path(g.id), params: { id: g.id, type: "Gossip" }, method: 'delete', class: 'btn btn-danger'%>
              <%else%>
                <%=button_to 'Liker', likes_path, params: { id: g.id, type: "Gossip" }, method: 'post', class: 'btn btn-warning'%>
              <%end%>
            <%end%>
          </div>
        </div>
      </div>
    <%end%>
</div>
</div>

app/views/gossips/new.html.erb
<div class="container">
  <div class="container-fluid mt-5">

    <% flash.each do |type, msg| %>
      <div class="alert alert-danger">
        <%= msg %>
      </div>
    <% end %>

    <h1>Créer un potin</h1>

      <%= form_tag url_for(action: 'create'), method: "post" do %>

      <div class="form-group">
      <%= label_tag 'Titre' %>
      <%= text_field_tag 'title','', require: true, class: "form-control"%>
      <br /> <br />
      </div>

      <div class="form-group">
      <%= label_tag 'Contenu' %>
      <%= text_area_tag 'content', '', require: true, class: "form-control"%>
      <br /> <br />
      </div>

      <%= submit_tag "Envoyer", class: "btn btn-primary"%>

    <% end %>

  </div>
</div>

app/views/gossips/show.html.erb
<div class="container">
  <div class="container-fluid mt-5">

    <%#Info de publication%>
    <% flash.each do |type, msg| %>
      <div class="alert alert-info">
        <%= msg %>
      </div>
    <% end %>

    <%#Entête%>
    <h1 class="display-3 mb-3"><%=@gossip.title%></h1>
    <h5 class="mb-2">Par <%=link_to "#{@gossip.user.first_name} #{@gossip.user.last_name}", { controller: 'user', action: 'show', id: @gossip.user.id }, class: "text-decoration-none"%></h5>
    <p>De <%=link_to "#{@gossip.user.city.name.capitalize}", { controller: 'city', action: 'show', id: @gossip.user.city.id }, class: "text-decoration-none"%></p>

    <%date = @gossip.created_at%>
    <p class="text-muted mb-4">Publié le <%=date.strftime('%d-%m-%Y')%></p>

    <%#Contenu%>
    <h3 class="h3 text-center mb-5"><%=@gossip.content%></h3>

    <figure class="text-end"> 
      <blockquote class="blockquote">
        <p class="text-muted">Ҫa ne veut rien dire, mais dans le contexte, je trouvais ça approprié...</p>
      </blockquote>
      <figcaption class="blockquote-footer">
        Roi Loth dans <cite title="Kaamelott">Kaamelott</cite>
      </figcaption>
    </figure>

    <% if object_creator?(@gossip)%>
      <div class="d-flex">
        <button class="btn btn-warning" style="margin-right: 1rem;"><%=link_to 'Modifier', { controller: 'gossips', action: 'edit', id: @gossip.id }, class: 'text-dark text-decoration-none'%></button>
        <%= button_to "Supprimer", @gossip, :method => :delete, class: "btn btn-danger", data: { confirm: "êtes-vous sûr?" } %>
      </div>
    <%else%>
      <%if liked?(@gossip)%>
        <%=button_to "Je n'aime plus", like_path(@gossip.id), params: { id: @gossip.id, type: "Gossip" }, method: 'delete', class: 'btn btn-danger'%>
      <%else%>
        <%=button_to 'Liker', likes_path, params: { id: @gossip.id, type: "Gossip" }, method: 'post', class: 'btn btn-warning'%>
      <%end%>
    <%end%>

    <div class="container mt-4 text-end">
      <small class="text-muted">Likes</small>
      <span class="badge bg-warning rounded-pill"><%=@gossip.likes.size%></span>
    </div>

    <%#Formulaire de commentaire%>
    <div class="container-fluid text-end mt-4">
      <%= form_tag(gossip_comments_path(@id), method: 'post') do%>
        <%=text_field_tag 'gossip_id', @id, type: 'hidden', class: 'form-control' %>
        <div class="form-group">
          <%=text_area_tag 'content', '', required: true, class: 'form-control'%>
        </div>
        <div class="form-group mt-3">
          <%=submit_tag 'Commenter', class: 'btn btn-primary' %>
        </div>
      <%end%>
    </div>

    <%#Affichage des commentaires%>
    <div class="container-fluid">
      <h2 class="mt-4">Commentaires</h2>
      <div class="list-group list-group-flush">
        <%@gossip.comments.each do |c|%>
          <div class="row list-group-item">
            <% u = c.user %>
            <strong class="text-muted"><%="#{u.first_name} #{u.last_name}"%></strong>
            <p ><%=c.content%></p>
            <%if object_creator?(c)%>
              <div class="container text-end mb-3" style="width: 100%;">
                <%=link_to 'Modifier', edit_gossip_comment_path(@gossip.id, c.id), class: 'btn btn-secondary flex-end'%>
              </div>
            <%end%>

            <div class="container-fluid text-end">
              <div class="list-group" style="width: 25rem;">
                <%c.comments.each do |cc|%>
                  <div class="row list-group-item">
                    <% uu = cc.user %>
                    <strong class="text-muted"><%="#{uu.first_name} #{uu.last_name}"%></strong>
                    <p><%=cc.content%></p>
                    <%if object_creator?(cc)%>
                      <div class="container mb-3" style="width: 100%;">
                        <%=link_to 'Modifier', edit_gossip_comment_comment_path(@gossip.id, c.id, cc.id), class: 'btn btn-secondary flex-end'%>
                      </div>
                    <%end%>
                  </div>
                <%end%>
              </div>
            </div>

          </div>
        <%end%>
      </div>
    </div>
  </div>
</div>