config/routes.rb
Rails.application.routes.draw do
  root 'gossips#index'
  resources :sessions, only: [:new, :create, :destroy]
  resources :user, only: [:show, :create, :new]
  resources :city, only: [:show]
  resources :likes, only: [:create, :destroy]

  resources :gossips do
    resources :likes, only: [:create, :destroy]
    resources :comments, except: [:index, :new] do
      resources :likes, only: [:create, :destroy]
      resources :comments, except: [:index, :new] do
        resources :likes, only: [:create, :destroy]
      end
    end
  end

  resources :contact, only: [:index]
  resources :team, only: [:index]
  

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord

  validates :name,
            presence: true

  validates :zip_code,
            presence: true

  has_many :users
end

app/models/comment.rb
class Comment < ApplicationRecord

  validates :comment_type_type,
            presence: true

  validates :comment_type_id,
            presence: true

  validates :content,
            presence: true,
            length: { maximum: 200 }

  has_many :likes, as: :like_target
  belongs_to :user
  belongs_to :comment_type, polymorphic: true
  has_many :comments, as: :comment_type
end

app/models/gossip.rb
class Gossip < ApplicationRecord

  validates :title,
            presence: true,
            length: { minimum: 3, maximum: 14 }

  validates :content,
            presence: true

  has_many :likes, as: :like_target
  belongs_to :user
  belongs_to :tag, optional: true
  has_many :comments, as: :comment_type
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :like_target, polymorphic: true
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord

  validates :content,
            presence: true,
            length: { maximum: 2000 }

  validates :sender_id,
            presence: true

  validates :recipient_id,
            presence: true

  belongs_to :sender, class_name: 'User'
  belongs_to :recipient, class_name: 'User'
end

app/models/tag.rb
class Tag < ApplicationRecord

  validates :title,
            presence: true,
            length: { minimum: 3, maximum: 20 }

  has_many :gossips
end

app/models/user.rb
class User < ApplicationRecord

  has_secure_password

  validates :first_name,
            presence: true

  validates :last_name,
            presence: true

  validates :email,
            presence: true,
            uniqueness: true,
            format: {
              with: /\A[^@\s]+@([^@\s]+.)+[^@\s]+\z/,
              message: 'email adress please'
            }

  validates :password,
            presence: true,
            length: { minimum: 6, maximum: 20 }

  validates :description,
            presence: true,
            length: { minimum: 20, maximum: 200 }

  has_many :gossips
  has_many :comments, as: :comment_type
  has_many :likes
  belongs_to :city
  has_many :sent_messages, foreign_key: 'sender_id', class_name: 'PrivateMessage'
  has_many :received_messages, foreign_key: 'recipient_id', class_name: 'PrivateMessage'

  def remember(remeber_token)
    remember_digest = BCrypt::Password.create(remeber_token)
    update(remember_digest: remember_digest)
  end
end

app/controllers/city_controller.rb
class CityController < ApplicationController
  def show
    @city = City.find(params[:id])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def show
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  before_action :authenticate_user

  def create
    @like = Like.create(
      user: current_user,
      like_target_id: params[:id],
      like_target_type: params[:type]
    )
    redirect_back(fallback_location: gossips_path)
  end

  def destroy
    @like = Like.where(like_target_id: params[:id], like_target_type: params[:type], user: current_user)
    @like[0].destroy
    redirect_back(fallback_location: gossips_path)
  end
end

app/controllers/team_controller.rb
class TeamController < ApplicationController
  def index 
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def show
    @user = current_user
  end

  def new
  end

  def create

    if exists?(params[:city])
      @city = find_city(params[:city])
    else
      @city = create_city(params[:city], params[:zip_code])
    end

    @user = User.new(
      first_name: params[:first_name],
      last_name: params[:last_name],
      email: params[:email],
      password: params[:password],
      description: params[:description],
      age: params[:age],
      city: @city
    )
    if @user.save
      log_in(@user)
      if params[:remember_user]
        remember(current_user)
      end
      redirect_to gossips_path, alert: "Bienvenue sur The Gossip Project #{current_user.first_name} !"
    else
      flash.now[:danger] = "Votre compte n'a pas pu être créé, vérifiez que vous avez rempli tous les champs"
      render :new
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/city_helper.rb
module CityHelper
  def exists?(city_name)
    return true if City.find_by(name: city_name.downcase)

    false
  end

  def find_city(name)
    City.find_by(name: name)
  end

  def create_city(name, zip_code)
    City.create(name: name.downcase, zip_code: zip_code.downcase)
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
  def liked?(content)
    c_likes = []
    content.likes.each do |l|
      c_likes << l.user
    end
    return true if c_likes.any? { |u| u == User.find_by(id: session[:user_id]) }

    false
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def current_user
    if session[:user_id]
      User.find_by(id: session[:user_id])
    elsif
      cookies[:user_id]
      # Trouver l'utilisateur en DB a partir de son id dans le cookie
      user = user.find_by(id: cookies[:user_id])
      if user
        # Comparaison du remember_token stocke en cookie hashe, avec le hash remember_digest en db
        remember_token = cookies[:remember_token]
        remember_digest = user.remember_digest
        user_authenticated = BCrypt::Password.new(remember_digest).is_password?(remember_token)

        if user_authenticated
          log_in(user)
          current_user = user
        end
      
      end
    end
  end

  def authenticate_user
    unless current_user
       redirect_to new_session_path, alert: 'Vous devez être connecté pour faire cela !'
    end
  end

  def remember(user)
    # Generation d'un token en base64
    remember_token = SecureRandom.urlsafe_base64

    # Stockage en base de donnees
    user.remember(remember_token)

    cookies.permanent[:user_id] = { value: user.id, same_site: :lax }
    cookies.permanent[:remember_token] = { value: remember_token, same_site: :lax }
  end

  def log_in(user)
    session[:user_id] = user.id
  end

  def forget(user)
    user.update(remember_digest: nil)
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

  def log_out(user)
    session.delete(:user_id)
    forget(user)
  end

  def object_creator?(content)
    return true if content.user == current_user

    false
  end

  def logged_in?
    return true unless session[:user_id].nil?

    false
  end
end

app/helpers/team_helper.rb
module TeamHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/city/show.html.erb
<div class="container mt-5">
  <div class="container-fluid">
    <h1 class="mb-2"><%=@city.name.capitalize%></h1>
    <h4 class="text-muted mb-5">Tous les potins de <%=@city.name.capitalize%></h4>
    <div class="container">
      <%@city.users.each do |u|%>
        <%u.gossips.each do |g|%>
          <div class="card mb-2">
            <div class="card-body">
              <h3 class="card-title"><%=g.title%></h3>
              <h5 class="card-text text-muted"><%=g.user.first_name%> <%=g.user.last_name%></h5>
              <div class="container text-end">
                <small class="text-muted">Comms</small>
                <span class="badge bg-primary rounded-pill"><%=g.comments.size%></span>
              </div>
              <div class="container text-end mt-3">
                <small class="text-muted">Likes</small>
                <span class="badge bg-warning rounded-pill"><%=g.likes.size%></span>
              </div>
              <div class="container d-flex">
                <button type="button" class="btn btn-primary" style="margin-right: 1rem;">
                  <%=link_to 'Voir', { controller: 'gossips', action: 'show', id: g.id }, class: "text-light", style: "text-decoration: none;"%>
                </button>
                <%if !object_creator?(g)%>
                  <%if liked?(g)%>
                    <%=button_to "Je n'aime plus", like_path(g.id), params: { id: g.id, type: "Gossip" }, method: 'delete', class: 'btn btn-danger'%>
                  <%else%>
                    <%=button_to 'Liker', likes_path, params: { id: g.id, type: "Gossip" }, method: 'post', class: 'btn btn-warning'%>
                  <%end%>
                <%end%>
              </div>
            </div>
          </div>
        <%end%>
    <%end%>

  </div>
</div>

app/views/user/new.html.erb
<div class="container">
  <div class="container-fluid mt-5">

    <%flash.each do |type, msg|%>
      <div class="alert alert-danger">
        <%=msg%>
      </div>
    <%end%>

    <h1>Inscription</h1>
    <div class="container">
      <%=form_tag(user_index_path, method: 'post') do%>
        <div class="form-group mt-3">
          <label class="h4">Prénom</label>
          <%=text_field_tag 'first_name', '', required: true, class: 'form-control'%>
        </div>
        <div class="form-group mt-3">
          <label class="h4">Nom</label>
          <%=text_field_tag 'last_name', '', required: true, class: 'form-control'%>
        </div>
        <div class="form-group mt-3">
          <label class="h4">Email</label>
          <%=text_field_tag 'email', '', required: true, class: 'form-control'%>
        </div>
        <div class="form-group mt-3">
          <label class="h4">Mot de passe</label>
          <%=password_field_tag 'password', '', required: true, class: 'form-control'%>
        </div>
        <div class="form-group mt-3">
          <label class="h4">Description</label>
          <%=text_area_tag 'description', '', required: true, class: 'form-control'%>
        </div>
        <div class="form-group mt-3">
          <label class="h4">Age</label>
          <%=text_field_tag 'age', '', required: true, class: 'form-control'%>
        </div>
        <div class="form-group mt-3">
          <label class="h4">Ville</label>
          <%=text_field_tag 'city', '', required: true, class: 'form-control'%>
        </div>
        <div class="form-group mt-3">
          <label class="h4">Code postal</label>
          <%=text_field_tag 'zip_code', '', required: true, class: 'form-control'%>
        </div>
        <div class="form-group mt-3">
          <%=check_box_tag 'remember_user'%>
          <label class="h5">Se rappeler de moi</label>
        </div>
        <%=submit_tag "S'inscrire", class: 'btn btn-primary mt-3'%>
      <%end%>
    </div>
  </div>
</div>

app/views/user/show.html.erb
<%u = User.find(params[:id])%>
<div class="container">
  <div class="container-fluid mt-5">
    <h1><%=u.first_name%> <%=u.last_name%></h1>
    <h3 class="text-muted"><%=u.age%> ans, de <%=link_to "#{u.city.name.capitalize}", { controller: 'city', action: 'show', id: u.city.id }, class: "text-decoration-none"%></h3>
    <h5 class="text-muted mb-5"><%=u.email%></h5>
    <p><%=u.description%></p>
  </div>
</div>