config/routes.rb
Rails.application.routes.draw do
  root 'gossips#index'
  resources :sessions, only: [:new, :create, :destroy]
  resources :user, only: [:show, :create, :new]
  resources :city, only: [:show]
  resources :likes, only: [:create, :destroy]

  resources :gossips do
    resources :likes, only: [:create, :destroy]
    resources :comments, except: [:index, :new] do
      resources :likes, only: [:create, :destroy]
      resources :comments, except: [:index, :new] do
        resources :likes, only: [:create, :destroy]
      end
    end
  end

  resources :contact, only: [:index]
  resources :team, only: [:index]
  

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord

  validates :name,
            presence: true

  validates :zip_code,
            presence: true

  has_many :users
end

app/models/comment.rb
class Comment < ApplicationRecord

  validates :comment_type_type,
            presence: true

  validates :comment_type_id,
            presence: true

  validates :content,
            presence: true,
            length: { maximum: 200 }

  has_many :likes, as: :like_target
  belongs_to :user
  belongs_to :comment_type, polymorphic: true
  has_many :comments, as: :comment_type
end

app/models/gossip.rb
class Gossip < ApplicationRecord

  validates :title,
            presence: true,
            length: { minimum: 3, maximum: 14 }

  validates :content,
            presence: true

  has_many :likes, as: :like_target
  belongs_to :user
  belongs_to :tag, optional: true
  has_many :comments, as: :comment_type
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :like_target, polymorphic: true
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord

  validates :content,
            presence: true,
            length: { maximum: 2000 }

  validates :sender_id,
            presence: true

  validates :recipient_id,
            presence: true

  belongs_to :sender, class_name: 'User'
  belongs_to :recipient, class_name: 'User'
end

app/models/tag.rb
class Tag < ApplicationRecord

  validates :title,
            presence: true,
            length: { minimum: 3, maximum: 20 }

  has_many :gossips
end

app/models/user.rb
class User < ApplicationRecord

  has_secure_password

  validates :first_name,
            presence: true

  validates :last_name,
            presence: true

  validates :email,
            presence: true,
            uniqueness: true,
            format: {
              with: /\A[^@\s]+@([^@\s]+.)+[^@\s]+\z/,
              message: 'email adress please'
            }

  validates :password,
            presence: true,
            length: { minimum: 6, maximum: 20 }

  validates :description,
            presence: true,
            length: { minimum: 20, maximum: 200 }

  has_many :gossips
  has_many :comments, as: :comment_type
  has_many :likes
  belongs_to :city
  has_many :sent_messages, foreign_key: 'sender_id', class_name: 'PrivateMessage'
  has_many :received_messages, foreign_key: 'recipient_id', class_name: 'PrivateMessage'

  def remember(remeber_token)
    remember_digest = BCrypt::Password.create(remeber_token)
    update(remember_digest: remember_digest)
  end
end

app/controllers/city_controller.rb
class CityController < ApplicationController
  def show
    @city = City.find(params[:id])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/city_helper.rb
module CityHelper
  def exists?(city_name)
    return true if City.find_by(name: city_name.downcase)

    false
  end

  def find_city(name)
    City.find_by(name: name)
  end

  def create_city(name, zip_code)
    City.create(name: name.downcase, zip_code: zip_code.downcase)
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
  def liked?(content)
    c_likes = []
    content.likes.each do |l|
      c_likes << l.user
    end
    return true if c_likes.any? { |u| u == User.find_by(id: session[:user_id]) }

    false
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def current_user
    if session[:user_id]
      User.find_by(id: session[:user_id])
    elsif
      cookies[:user_id]
      # Trouver l'utilisateur en DB a partir de son id dans le cookie
      user = user.find_by(id: cookies[:user_id])
      if user
        # Comparaison du remember_token stocke en cookie hashe, avec le hash remember_digest en db
        remember_token = cookies[:remember_token]
        remember_digest = user.remember_digest
        user_authenticated = BCrypt::Password.new(remember_digest).is_password?(remember_token)

        if user_authenticated
          log_in(user)
          current_user = user
        end
      
      end
    end
  end

  def authenticate_user
    unless current_user
       redirect_to new_session_path, alert: 'Vous devez être connecté pour faire cela !'
    end
  end

  def remember(user)
    # Generation d'un token en base64
    remember_token = SecureRandom.urlsafe_base64

    # Stockage en base de donnees
    user.remember(remember_token)

    cookies.permanent[:user_id] = { value: user.id, same_site: :lax }
    cookies.permanent[:remember_token] = { value: remember_token, same_site: :lax }
  end

  def log_in(user)
    session[:user_id] = user.id
  end

  def forget(user)
    user.update(remember_digest: nil)
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

  def log_out(user)
    session.delete(:user_id)
    forget(user)
  end

  def object_creator?(content)
    return true if content.user == current_user

    false
  end

  def logged_in?
    return true unless session[:user_id].nil?

    false
  end
end

app/helpers/team_helper.rb
module TeamHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TheGossipProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%#Stylesheets%>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-wEmeIV1mKuiNpC+IOBjI7aAzPcEZeedi5yW5f2yOq55WWLwNGmvvx4Um1vskeMj0" crossorigin="anonymous">

  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
          <%= link_to 'The Gossip Project', gossips_path, class: "navbar-brand"%>
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <%= link_to "L'équipe", team_index_path, class: "nav-link"%>
            </li>

            <li class="nav-item">
              <%= link_to "Contact", contact_index_path, class: "nav-link"%>
            </li>

            <% if logged_in?%>
              <li class="nav-item" style="margin-left: 1rem;">
                <%= button_to "Déconnexion", session_path(:id), method: 'delete', class: "btn btn-secondary"%>
              </li>
            <%else%>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                 S'inscrire / Se connecter 
                </a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                    <li><%= link_to "S'inscrire", new_user_path, class: "dropdown-item"%></li>
                    <li><%= link_to "Se connecter", new_session_path, class: "dropdown-item"%></li>
                </ul>
            <%end%>
            </li>
          <ul>
        </div>
      </nav>
    </header>
    <%= yield %>

    <%#Scripts bootstrap%>

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.min.js" integrity="sha384-lpyLfhYuitXl2zRZ5Bn2fqnhNAKOAaM/0Kr9laMspuaMiZfGmfwRNFh8HlMy49eQ" crossorigin="anonymous"></script>
  </body>
</html>